version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - run:
          name: Set permission for gradlew
          command: sudo chmod +x ./gradlew
      - run:
          name: Build the app
          command: ./gradlew build

  deploy:
    executor: android/android
    steps:
        - checkout
        - run:
            name: Set permission for gradlew
            command: sudo chmod +x ./gradlew
        - run:
            name: Assemble and deploy to AppCenter
            command: ./gradlew appCenterAssembleAndUploadAlphaRelease
